#!/bin/bash
Delete=$(git status --porcelain -s| grep D| cut -d ' ' -f 3)
Modify=$(git status --porcelain -s| grep M| cut -d ' ' -f 3| head -n1)
Add=$(git status --porcelain -s| grep ??| cut -d ' ' -f 2| head -n1)
directory=$(if [ -d "${Add}" ]; then echo `basename "$PWD"`; else echo $Add; fi)
file=$(if [ -f "${Add}" ] || [ -f "${Modify}" ]; then echo " file"; else echo " with README.md file";fi)

if [[ `git status --porcelain --untracked-files=no| grep D` ]]; then
  git add $printf $Delete && git commit -m "Deleting:$printf $Delete" && git push -u origin main
elif [[ `git status --porcelain --untracked-files=no| grep M` ]]; then
  git add $printf $Modify && git commit -m "Updating `file -b $printf $Modify`$file:$printf $Modify" && git push -u origin main
else
  git add $Add && git commit -m "Adding `file -b $Add`$file: $directory" && git push -u origin main
fi
